apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bolcd.fullname" . }}
  labels:
    app: {{ include "bolcd.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "bolcd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bolcd.name" . }}
    spec:
      serviceAccountName: {{ include "bolcd.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          {{- end }}
          env:
            {{- if and .Values.apiKeysSecret .Values.apiKeysSecret.enabled }}
            - name: BOLCD_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiKeysSecret.name | quote }}
                  key: {{ .Values.apiKeysSecret.key | quote }}
            {{- else }}
            - name: BOLCD_API_KEYS
              value: {{ .Values.env.BOLCD_API_KEYS | quote }}
            {{- end }}
          {{- if .Values.envVars }}
          {{- range .Values.envVars }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.secretEnv }}
          {{- range .Values.secretEnv }}
            - name: {{ .name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName | quote }}
                  key: {{ .secretKey | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.envFromSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecretName | quote }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep {{ .Values.pod.preStopSleepSeconds | default 5 }}"]
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          {{- if or .Values.logs.emptyDir (and .Values.persistence .Values.persistence.logs .Values.persistence.logs.enabled) .Values.extraVolumeMounts .Values.reportsPVC.enabled (.Values.configsPVC.enabled) }}
          volumeMounts:
            {{- if or (.Values.logs.emptyDir) (and .Values.persistence .Values.persistence.logs .Values.persistence.logs.enabled) }}
            - name: logs
              mountPath: /app/logs
            {{- end }}
            {{- if .Values.reportsPVC.enabled }}
            - name: reports
              mountPath: /reports
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.pod.terminationGraceSeconds | default 30 }}
      {{- if or .Values.logs.emptyDir (and .Values.persistence .Values.persistence.logs .Values.persistence.logs.enabled) .Values.extraVolumes .Values.reportsPVC.enabled (.Values.configsPVC.enabled) }}
      volumes:
        {{- if and .Values.persistence .Values.persistence.logs .Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logs.existingClaim | default (include "bolcd.fullname" .) }}-logs
        {{- else if .Values.logs.emptyDir }}
        - name: logs
          emptyDir: {}
        {{- end }}
        {{- if .Values.reportsPVC.enabled }}
        - name: reports
          persistentVolumeClaim:
            claimName: {{ .Values.reportsPVC.existingClaim | default (include "bolcd.fullname" .) }}-reports
        {{- end }}
        {{- if .Values.configsPVC.enabled }}
        - name: configs
          persistentVolumeClaim:
            claimName: {{ .Values.configsPVC.existingClaim | default (include "bolcd.fullname" .) }}-configs
        {{- end }}
        {{- with .Values.extraVolumes }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- end }}

