apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bolcd.fullname" . }}
  labels:
    app: {{ include "bolcd.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bolcd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bolcd.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: BOLCD_API_KEYS
              value: {{ .Values.env.BOLCD_API_KEYS | quote }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20

