{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bolcd.fullname" . }}-np
  labels:
    app: {{ include "bolcd.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "bolcd.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- if .Values.networkPolicy.ingressFromCIDRs }}
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          {{- range .Values.networkPolicy.ingressFromCIDRs }}
            - {{ . | quote }}
          {{- end }}
      {{- end }}
      - namespaceSelector: {}
      - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}


