apiVersion: v1
kind: Service
metadata:
  name: {{ include "bolcd.fullname" . }}
  labels:
    app: {{ include "bolcd.name" . }}
  {{- if .Values.monitor.serviceAnnotationsEnabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "bolcd.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

