image:
  repository: ghcr.io/fitydo/bol-cd
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

env:
  BOLCD_API_KEYS: "view:viewer,testop:operator"

resources: {}

securityContext: {}
podSecurityContext: {}

logs:
  emptyDir: false

apiKeysSecret:
  enabled: false
  name: bolcd-apikeys
  key: BOLCD_API_KEYS

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  exposeMetrics: false
  basicAuth:
    enabled: false
    secretName: bolcd-basic-auth
    realm: "Authentication Required"
  whitelistSourceRanges: []
  tls: []

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: false
  minAvailable: 1

networkPolicy:
  enabled: false
  ingressFromCIDRs: []

persistence:
  logs:
    enabled: false
    size: 1Gi
    storageClass: ""
    existingClaim: ""

monitor:
  serviceAnnotationsEnabled: false
  serviceMonitorEnabled: false
  prometheusRelease: prometheus
  scrapeInterval: 30s

backup:
  enabled: false
  # Option A: copy archives to an extra PVC
  pvc:
    enabled: false
    size: 10Gi
    storageClass: ""
    existingClaim: ""
  # Option B: upload to S3-compatible storage
  s3:
    enabled: false
    bucket: "your-bucket"
    prefix: "bolcd"
    region: "us-east-1"
    endpoint: ""  # optional (e.g., MinIO)
    awsSecretName: bolcd-backup-aws  # secret with AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY
  image: "alpine:3.20"
  schedule: "0 2 * * *"

